import = [
  "~/.config/alacritty/tokyonight_night.toml"
]
# enable_experimental_conpty_backend = false
live_config_reload = true

[bell]
animation = "EaseOutExpo"
color = "0xffffff"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true


# [colors.hints.end]
# background = "#4C566A"
# foreground = "#81A1C1"
#
# [colors.hints.start]
# background = "#4C566A"
# foreground = "#B988B0"

# [colors.normal]
# black = "#3B4252"
# blue = "#81A1C1"
# cyan = "#88C0D0"
# green = "#A3BE8C"
# magenta = "#B988B0"
# red = "#BF616A"
# white = "#E5E9F0"
# yellow = "#EBCB8B"

# [colors.primary]
# background = "#2E3440"
# foreground = "#C8D0E0"

# [colors.search.focused_match]
# background = "#4C566A"
# foreground = "#EBCB8B"

# [colors.search.footer_bar]
# background = "#434C5E"
# foreground = "#88C0D0"

# [colors.search.matches]
# background = "#4C566A"
# foreground = "#81A1C1"
#
# [colors.selection]
# background = "#3F4758"
# text = "CellForeground"

[cursor]
style = "Block"
unfocused_hollow = true

[debug]
log_level = "Warn"
persistent_logging = false
render_timer = false

[env]
TERM = "xterm-256color"

[font]
size = 10.0

[font.bold]
family = "RobotoMono Nerd Font"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "RobotoMono Nerd Font"
style = "Italic"

[font.normal]
family = "RobotoMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Paste"
key = "Paste"

[[keyboard.bindings]]
action = "PasteSelection"
key = "Insert"
mods = "Shift"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"

[[keyboard.bindings]]
action = "ClearLogNotice"
key = "L"
mods = "Control"

[[keyboard.bindings]]
chars = "\f"
key = "L"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001BOH"
key = "Home"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "\u001B[H"
key = "Home"
mode = "~AppCursor"

[[keyboard.bindings]]
chars = "\u001BOF"
key = "End"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "\u001B[F"
key = "End"
mode = "~AppCursor"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[5;2~"
key = "PageUp"
mode = "Alt"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[5;5~"
key = "PageUp"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[5~"
key = "PageUp"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[6;2~"
key = "PageDown"
mode = "Alt"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[6;5~"
key = "PageDown"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[6~"
key = "PageDown"

[[keyboard.bindings]]
chars = "\u001B[Z"
key = "Tab"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u007F"
key = "Back"

[[keyboard.bindings]]
chars = "\u001B\u007F"
key = "Back"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[2~"
key = "Insert"

[[keyboard.bindings]]
chars = "\u001B[3~"
key = "Delete"

[[keyboard.bindings]]
chars = "\u001B[1;2D"
key = "Left"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[1;5D"
key = "Left"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;3D"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[D"
key = "Left"
mode = "~AppCursor"

[[keyboard.bindings]]
chars = "\u001BOD"
key = "Left"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "\u001B[1;2C"
key = "Right"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[1;5C"
key = "Right"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;3C"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[C"
key = "Right"
mode = "~AppCursor"

[[keyboard.bindings]]
chars = "\u001BOC"
key = "Right"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "\u001B[1;2A"
key = "Up"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[1;5A"
key = "Up"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;3A"
key = "Up"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[A"
key = "Up"
mode = "~AppCursor"

[[keyboard.bindings]]
chars = "\u001BOA"
key = "Up"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "\u001B[1;2B"
key = "Down"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[1;5B"
key = "Down"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;3B"
key = "Down"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[B"
key = "Down"
mode = "~AppCursor"

[[keyboard.bindings]]
chars = "\u001BOB"
key = "Down"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "\u001BOP"
key = "F1"

[[keyboard.bindings]]
chars = "\u001BOQ"
key = "F2"

[[keyboard.bindings]]
chars = "\u001BOR"
key = "F3"

[[keyboard.bindings]]
chars = "\u001BOS"
key = "F4"

[[keyboard.bindings]]
chars = "\u001B[15~"
key = "F5"

[[keyboard.bindings]]
chars = "\u001B[17~"
key = "F6"

[[keyboard.bindings]]
chars = "\u001B[18~"
key = "F7"

[[keyboard.bindings]]
chars = "\u001B[19~"
key = "F8"

[[keyboard.bindings]]
chars = "\u001B[20~"
key = "F9"

[[keyboard.bindings]]
chars = "\u001B[21~"
key = "F10"

[[keyboard.bindings]]
chars = "\u001B[23~"
key = "F11"

[[keyboard.bindings]]
chars = "\u001B[24~"
key = "F12"

[[keyboard.bindings]]
chars = "\u001B[1;2P"
key = "F1"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[1;2Q"
key = "F2"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[1;2R"
key = "F3"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[1;2S"
key = "F4"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[15;2~"
key = "F5"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[17;2~"
key = "F6"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[18;2~"
key = "F7"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[19;2~"
key = "F8"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[20;2~"
key = "F9"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[21;2~"
key = "F10"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[23;2~"
key = "F11"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[24;2~"
key = "F12"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[1;5P"
key = "F1"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;5Q"
key = "F2"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;5R"
key = "F3"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;5S"
key = "F4"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[15;5~"
key = "F5"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[17;5~"
key = "F6"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[18;5~"
key = "F7"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[19;5~"
key = "F8"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[20;5~"
key = "F9"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[21;5~"
key = "F10"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[23;5~"
key = "F11"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[24;5~"
key = "F12"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;6P"
key = "F1"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[1;6Q"
key = "F2"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[1;6R"
key = "F3"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[1;6S"
key = "F4"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[15;6~"
key = "F5"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[17;6~"
key = "F6"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[18;6~"
key = "F7"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[19;6~"
key = "F8"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[20;6~"
key = "F9"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[21;6~"
key = "F10"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[23;6~"
key = "F11"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[24;6~"
key = "F12"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[1;3P"
key = "F1"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001B[1;3Q"
key = "F2"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001B[1;3R"
key = "F3"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001B[1;3S"
key = "F4"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001B[15;3~"
key = "F5"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001B[17;3~"
key = "F6"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001B[18;3~"
key = "F7"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001B[19;3~"
key = "F8"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001B[20;3~"
key = "F9"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001B[21;3~"
key = "F10"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001B[23;3~"
key = "F11"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001B[24;3~"
key = "F12"
mods = "Super"

[[keyboard.bindings]]
chars = """

"""
key = "NumpadEnter"

[[keyboard.bindings]]
chars = ""
key = "Back"
mods = "Control"

[[keyboard.bindings]]
chars = " "
key = "Space"
mods = "Alt"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Equals"
mods = "Control"

[mouse]
hide_when_typing = false

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

# [mouse.double_click]
# threshold = 300

# [mouse.hints]
# launcher = "xdg-open"
# modifiers = "None"

# [mouse.triple_click]
# threshold = 300

# [schemes.gruvbox.primary]
# background = "#282828"
# foreground = "#ebdbb2"
#
# [schemes.gruvbox.primary.bright]
# black = "#928374"
# blue = "#83a598"
# cyan = "#8ec07c"
# green = "#b8bb26"
# magenta = "#d3869b"
# red = "#fb4934"
# white = "#ebdbb2"
# yellow = "#fabd2f"
#
# [schemes.gruvbox.primary.normal]
# black = "#282828"
# blue = "#458588"
# cyan = "#689d6a"
# green = "#98971a"
# magenta = "#b16286"
# red = "#cc241d"
# white = "#a89984"
# yellow = "#d79921"
#
# [schemes.nord.bright]
# black = "0x4C566A"
# blue = "0x81A1C1"
# cyan = "0x8FBCBB"
# green = "0xA3BE8C"
# magenta = "0xB48EAD"
# red = "0xBF616A"
# white = "0xECEFF4"
# yellow = "0xEBCB8B"
#
# [schemes.nord.cursor]
# cursor = "0xD8DEE9"
# text = "0x2E3440"
#
# [schemes.nord.normal]
# black = "0x3B4252"
# blue = "0x81A1C1"
# cyan = "0x88C0D0"
# green = "0xA3BE8C"
# magenta = "0xB48EAD"
# red = "0xBF616A"
# white = "0xE5E9F0"
# yellow = "0xEBCB8B"
#
# [schemes.nord.primary]
# background = "0x2E3440"
# foreground = "0xD8DEE9"
#
# [schemes.onenord.bright]
# black = "#4C566A"
# blue = "#81A1C1"
# cyan = "#8FBCBB"
# green = "#A3BE8C"
# magenta = "#B988B0"
# red = "#BF616A"
# white = "#ECEFF4"
# yellow = "#EBCB8B"
#
# [schemes.onenord.hints.end]
# background = "#4C566A"
# foreground = "#81A1C1"
#
# [schemes.onenord.hints.start]
# background = "#4C566A"
# foreground = "#B988B0"
#
# [schemes.onenord.normal]
# black = "#3B4252"
# blue = "#81A1C1"
# cyan = "#88C0D0"
# green = "#A3BE8C"
# magenta = "#B988B0"
# red = "#BF616A"
# white = "#E5E9F0"
# yellow = "#EBCB8B"
#
# [schemes.onenord.primary]
# background = "#2E3440"
# foreground = "#C8D0E0"
#
# [schemes.onenord.search.focused_match]
# background = "#4C566A"
# foreground = "#EBCB8B"
#
# [schemes.onenord.search.footer_bar]
# background = "#434C5E"
# foreground = "#88C0D0"
#
# [schemes.onenord.search.matches]
# background = "#4C566A"
# foreground = "#81A1C1"
#
# [schemes.onenord.selection]
# background = "#3F4758"
# text = "CellForeground"

[scrolling]
history = 10000
multiplier = 1

[selection]
save_to_clipboard = false
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>"

[shell]
program = "/bin/zsh"

[window]
decorations = "none"
dynamic_padding = false
dynamic_title = true
opacity = 1
startup_mode = "Windowed"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 0
y = 0
